#!/bin/bash

echo "Enter domain (Without URL)"

read -r domain

chromium "https://centralops.net/co/DomainDossier.aspx?addr=$domain&dom_whois=true&dom_dns=true&net_whois=true"
chromium "https://dnslytics.com/domain/$domain"
chromium "https://domainbigdata.com/$domain"
chromium "https://whois.easycounter.com/$domain"
chromium "https://www.google.com/search?q=site:*.$domain+-www"
chromium "https://securitytrails.com/list/apex_domain/$domain"
chromium "https://api.hackertarget.com/hostsearch/?q=$domain"
chromium "https://searchdns.netcraft.com/?restriction=site+contains&host=*.$domain&lookup=wait..&position=limited"
chromium "https://www.virustotal.com/gui/domain/$domain"
chromium "https://archive.md/$domain"
chromium "https://vefsafn.is/?page=wayback-results&site=https://$domain"
chromium "https://arquivo.pt/page/search?hitsPerPage=10&query=https://$domain"
chromium "https://haw.nsk.hr/wayback/*/https://$domain"
chromium "https://archive-it.org/explore?q=$domain&show=Sites"
chromium "http://classic.oldweb.today/chrome/20081013170402/$domain"
chromium "https://web.archive.org/web/*/$domain"
chromium "http://arhiv.nuk.uni-lj.si/wayback/*/https://$domain"
chromium "https://swap.stanford.edu/*/https://$domain"
chromium "http://webcache.googleusercontent.com/search?q=cache:$domain"
chromium "https://web.archive.org/web/*/$domain/*"
chromium "https://openlinkprofiler.org/r/$domain"
chromium "https://www.threatcrowd.org/graphHtml.php?domain=$domain"
chromium "https://dnshistory.org/historical-dns-records/soa/$domain"
chromium "https://viewdns.info/propagation/?domain=$domain&type=6"
chromium "https://www.whatsmydns.net/#A/$domain"
chromium "https://domaineye.com/reverse-mx/mx.$domain"
chromium "https://securitytrails.com/domain/$domain/history/mx"
chromium "https://analyzeid.com/id/$domain"
chromium "https://crt.sh/?q=$domain"
chromium "https://censys.io/certificates?q=$domain"
chromium "https://whatcms.org/?s=$domain"
chromium "http://$domain/robots.txt"
chromium "https://www.google.com/search?q=site:$domain%20ext:bkf%20%7C%20ext:bkp%20%7C%20ext:bak%20%7C%20ext:old%20%7C%20ext:backup"
chromium "https://www.google.com/search?q=site:$domain%20ext:php%20intitle:phpinfo%20%27published%20by%20the%20PHP%20Group%27"
chromium "https://www.google.com/search?q=site%3A$domain+intitle%3Aindex.of++%7C+%22parent+directory%22"
chromium "https://www.google.com/search?q=site%3A$domain+intext%3A%22sql+syntax+near%22+%7C+intext%3A%22syntax+error+has+occurred%22+%7C+intext%3A%22incorrect+syntax+near%22+%7C+intext%3A%22unexpected+end+of+SQL+command%22+%7C+intext%3A%22Warning%3A+mysql_connect%28%29%22+%7C+intext%3A%22Warning%3A+mysql_query%28%29%22+%7C+intext%3A%22Warning%3A+pg_connect%28%29%22+%7C+filetype%3Asqlext%3Asql+%7C+ext%3Adbf+%7C+ext%3Amdb"
chromium "https://www.google.com/search?q=site:$domain%20inurl:php?=id1%20%7C%20inurl:index.php?id=%20%7C%20inurl:pageid=%20%7C%20inurl:.php"
chromium "https://www.google.com/search?q=site:$domain%20inurl:login%20%7C%20inurl:signin%20%7C%20intitle:Login%20%7C%20intitle:%20signin%20%7C%20inurl:auth"
chromium "https://www.google.com/search?q=site:*.$domain"
chromium "https://www.google.com/search?q=site%3Apastebin.com+%7C+site%3Apaste2.org+%7C+site%3Apastehtml.com+%7C+site%3Aslexy.org+%7C+site%3Asnipplr.com+%7C+site%3Asnipt.net+%7C+site%3Atextsnip.com+%7C+site%3Abitpaste.app+%7C+site%3Ajustpaste.it+%7C+site%3Aheypasteit.com+%7C+site%3Ahastebin.com+%7C+site%3Adpaste.org+%7C+site%3Adpaste.com+%7C+site%3Acodepad.org+%7C+site%3Ajsitor.com+%7C+site%3Acodepen.io+%7C+site%3Ajsfiddle.net+%7C+site%3Adotnetfiddle.net+%7C+site%3Aphpfiddle.org+%7C+site%3Aide.geeksforgeeks.org+%7C+site%3Arepl.it+%7C+site%3Aideone.com+%7C+site%3Apaste.debian.net+%7C+site%3Apaste.org+%7C+site%3Apaste.org.ru+%7C+site%3Acodebeautify.org++%7C+site%3Acodeshare.io+%7C+site%3Atrello.com+%22$domain%22"
chromium "https://www.google.com/search?q=site%3A$domain+%22password%22+filetype%3Adoc+%7C+filetype%3Apdf+%7C+filetype%3Adocx+%7C+filetype%3Axls+%7C+filetype%3Adat+%7C+filetype%3Alog"
chromium "https://www.google.com/search?q=site%3A.s3.amazonaws.com+%22$domain%22"
chromium "https://www.ssllabs.com/ssltest/analyze.html?d=$domain"
chromium "https://www.reddit.com/search?q=site:$domain&restrict_sr=&sort=relevance&t=all"
chromium "https://nitter.domain.glass/search?f=tweets&q=%22$domain%22&since=&until=&near="
chromium "https://github.com/search?q=%22$domain%22&type="
chromium "https://www.google.com/search?q=site%3Astackoverflow.com+%22$domain%22"
chromium "https://intelx.io/?s=$domain"
chromium "http://a.devs.today/$domain"



