#!/bin/bash

cd $HOME/Tools/SocialPath || exit
python3 manage.py makemigrations social &
python3 manage.py migrate social &
python3 manage.py migrate &
python3 manage.py runserver &
firefox http://localhost:8000/search
