#!/bin/bash

a="_0"
aa="_00"

echo "Enter ID (Only Numbers)"

read -r iid

chromium "https://vk.com/feed?obj=$iid&q=&section=mentions"
chromium "https://vk.com/photos$iid?act=comments"
chromium "https://vk.com/video/@id$iid"
chromium "https://vk.com/photos$iid"
chromium "https://vk.com/album$iid$a"
chromium "https://vk.com/album$iid$aa"
chromium "https://vk.com/feed?section=source&source=$iid"
chromium "https://vk.com/notes$iid"
chromium "https://vk.com/friends?id=$iid&section=subscribers"
chromium "https://vk.com/friends?id=$iid&section=phonebook"
chromium "https://bigbookname.com/user/id-$iid"
chromium "https://vk.com/wall$iid?q=type%3Areply"
chromium "https://vk.com/wall$iid?q=type%3Acopy"
chromium "https://vk.com/wall$iid?q=type%3Aphoto"
chromium "https://vk.com/wall$iid?q=type%3Avideo"
chromium "https://vk.com/wall$iid?q=type%3Aaudio"
chromium "https://vk.com/wall$iid?q=type%3Adoc"
chromium "https://vk.com/wall$iid?q=type%3Alink"
chromium "https://vk.com/wall$iid?q=type%3Apoll"
chromium "https://vk.com/wall$iid?q=type%3Aarticle"
chromium "https://vk.com/wall$iid?q=type%3Anote"
chromium "https://vk.com/wall$iid?q=type%3Apage"
chromium "https://vk.com/wall$iid?q=type%3Aalbum"
chromium "https://vk.com/wall$iid?q=type%3Anone"
chromium "https://vk.com/foaf.php?id=$iid"
chromium "https://webcache.googleusercontent.com/search?q=cache:vk.com/id$iid"
chromium "https://web.archive.org/web/*/https://vk.com/id$iid"
chromium "https://web.archive.org/web/*/https://m.vk.com/id$iid"
chromium "https://archive.md/http://vk.com/id$iid"
chromium "https://webcache.googleusercontent.com/search?q=cache:vkontakte.ru/id$iid"
chromium "https://web.archive.org/web/*/https://vkontakte.ru/id$iid"
chromium "https://archive.md/http://vkontakte.ru/id$iid"
chromium "https://yandex.ru/search/?text=%22id$iid%22&lr=213&redircnt=1637951417.1"
