#!/usr/bin/env bash


timestamp=$(date +%Y-%m-%d:%H:%M)

domain=$(zenity --entry --width=300 --title "Sublist3r" --text "Enter target domain name" --entry-text "" 2> >(grep -v 'GtkDialog' >&2))
echo $domain
if [ ! -z "$domain" ]; then
	echo "verify legit domain"
	if [[ $domain =~ $fqdnregex ]]; then
		mkdir /home/user/Cases/$domain
		#Run Tool
		sublist3r -d $domain -v -o /home/user/Cases/$domain/sublist3r-b_$domain.txt |tee >(zenity --progress --pulsate --no-cancel --auto-close --text="Sublist3r search, please wait...")
		sed -i 's/<BR>/\n/' /home/user/Cases/$domain/sublist3r-b_$domain.txt
		FILE=/home/user/Cases/$domain/tmp-$domain.txt
		if test -f "$FILE"; then
			cat /home/user/Cases/$domain/sublist3r-b_$domain.txt | sort -u | tee -a /home/user/Cases/$domain/tmp-$domain.txt
			cat /home/user/Cases/$domain/tmp-$domain.txt | sort -u > /tmp/tmp.txt
			cat /tmp/tmp.txt > /home/user/Cases/$domain/tmp-$domain.txt 
			rm /tmp/tmp.txt
		else
			cat /home/user/Cases/$domain/sublist3r-b_$domain.txt | sort -u | tee /home/user/Cases/$domain/tmp-$domain.txt
		fi

	else
		zenity --error --width=300 --text "Doesn't appear to be a legitimate domain, exiting!" 2> >(grep -v 'GtkDialog' >&2)
		exit
	fi
	
	#Run Tool
	theHarvester -d $domain -b all -f /home/user/Cases/$domain/$timestamp-theharvester-$domain.html |tee >(zenity --progress --pulsate --no-cancel --auto-close --text="theHarvester search, please wait...")
	if [ -f /home/user/Cases/$timestamp-theharvester-$domain.html  ]; then
		screen -d -m firefox /home/user/Cases/$timestamp-theharvester-$domain.html	
	fi
	
	#Run Tool
	photon -u $domain -v --wayback --clone --keys --dns -l 3 -t 100 -o /home/user/Cases/$domain

	#Run Tool
	lynx -dump $domain | tee -a /home/user/Cases/$domain/site-links-$domain.txt 
	
	#Run Tool
	amass intel -whois -ip -src -d $domain  -o /home/user/Cases/$domain/amass-$timestamp-$domain.1.txt 
	amass enum -src -brute -d $domain -o /home/user/Cases/$domain/amass-$timestamp-$domain.2.txt -d $domain 
				
	#Run Tool
	/opt/csitools/decloud $domain | tee /home/user/Cases/$domain/decloud-$domain.txt 
	filename=/home/user/Cases/$domain/decloud-$domain.txt
	if test -f "$FILE"; then
		cat /home/user/Cases/$domain/decloud-$domain.txt | grep "Checking" | cut -d" " -f4 | sed 's/<BR>/\n/' | sort -u | tee -a /home/user/Cases/$domain/tmp-$domain.txt
		cat /home/user/Cases/$domain/tmp-$domain.txt | sed 's/<BR>/\n/' | sort -u > /tmp/tmp.txt
		cat /tmp/tmp.txt > /home/user/Cases/$domain/tmp-$domain.txt 
		rm /tmp/tmp.txt	
	else
		cat /home/user/Cases/$domain/decloud-$domain.txt | grep "Checking" | cut -d" " -f4 | sed 's/<BR>/\n/' | sort -u | tee /home/user/Cases/$domain/tmp-$domain.txt
	fi
	gedit /home/user/Cases/$domain/tmp-$domain.txt &		

	if zenity --question --text="Would you like to open the findings in a browser?"; then
		while read links; do 
		    echo "Opening: $links"; screen -d -m firefox $links
		done < $FILE
		echo "Please wait for Firefox to open..."
	else
		echo "Done."
	fi 

	#Run Tool 
	mkdir /home/user/Cases/$domain/download-files
	metagoofil -d $domain -w -t pdf,doc,xls,ppt,docx,xlsx,pptx -o "/home/user/Cases/$domain/download-files"
	thunar /home/user/Cases/$domain >/dev/null 2>&1
	exit
	
fi
