#!/usr/bin/env bash


timestamp=$(date +%Y-%m-%d:%H:%M)

domain=$(zenity --entry --width=300 --title "Sublist3r" --text "Enter target domain name" --entry-text "" 2> >(grep -v 'GtkDialog' >&2))
echo $domain
if [ ! -z "$domain" ]; then
	echo "verify legit domain"
	if [[ $domain =~ $fqdnregex ]]; then
		mkdir /root/Cases/$domain
		#Run Tool
		sublist3r -d $domain -v -o /root/Cases/$domain/sublist3r-b_$domain.txt |tee >(zenity --progress --pulsate --no-cancel --auto-close --text="Sublist3r search, please wait...")
		sed -i 's/<BR>/\n/' /root/Cases/$domain/sublist3r-b_$domain.txt
		FILE=/root/Cases/$domain/tmp-$domain.txt
		if test -f "$FILE"; then
			cat /root/Cases/$domain/sublist3r-b_$domain.txt | sort -u | tee -a /root/Cases/$domain/tmp-$domain.txt
			cat /root/Cases/$domain/tmp-$domain.txt | sort -u > /tmp/tmp.txt
			cat /tmp/tmp.txt > /root/Cases/$domain/tmp-$domain.txt 
			rm /tmp/tmp.txt
		else
			cat /root/Cases/$domain/sublist3r-b_$domain.txt | sort -u | tee /root/Cases/$domain/tmp-$domain.txt
		fi

	else
		zenity --error --width=300 --text "Doesn't appear to be a legitimate domain, exiting!" 2> >(grep -v 'GtkDialog' >&2)
		exit
	fi
	
	#Run Tool
	theHarvester -d $domain -b baidu,bing,google,yahoo,virustotal,certspotter,crtsh,dnsdumpster,duckduckgo,exalead,hackertarget,intelx,hunter,netcraft,otx,pentesttools,projectdiscovery,qwant,rapiddns,securityTrails,sublist3r,threatcrowd,threatminer,trello,twitter,urlscan -f /root/Cases/$domain/$timestamp-theharvester-$domain.html |tee >(zenity --progress --pulsate --no-cancel --auto-close --text="theHarvester search, please wait...")
	if [ -f /root/Cases/$timestamp-theharvester-$domain.html  ]; then
		screen -d -m firefox /root/Cases/$timestamp-theharvester-$domain.html	
	fi
	
	#Run Tool
	photon -u $domain -v -l 3 -t 100 -o /root/Cases/$domain |tee >(zenity --progress --pulsate --no-cancel --auto-close --text="photon search, please wait...")

	#Run Tool
	lynx -dump $domain | tee -a /root/Cases/$domain/site-links-$domain.txt |tee >(zenity --progress --pulsate --no-cancel --auto-close --text="lynx search, please wait...")
	
	#Run Tool
	amass intel -whois -ip -src -d $domain  -o /root/Cases/$domain/amass-$timestamp-$domain.1.txt |tee >(zenity --progress --pulsate --no-cancel --auto-close --text="Amass intel search, please wait...")
	amass enum -src -brute -d $domain -o /root/Cases/$domain/amass-$timestamp-$domain.2.txt -d $domain |tee >(zenity --progress --pulsate --no-cancel --auto-close --text="Amass enum search, please wait...")
				
	#Run Tool
	/opt/csitools/decloud $domain | tee /root/Cases/$domain/decloud-$domain.txt |tee >(zenity --progress --pulsate --no-cancel --auto-close --text="De-Cloud search, please wait...")
36189.txt | grep "Checking" | cut -d" " -f4 | sed 's/<BR>/\n/' | sort -u | tee -a /root/Cases/$domain/tmp-$domain.txt
		cat /root/Cases/$domain/tmp-$domain.txt | sed 's/<BR>/\n/' | sort -u > /tmp/tmp.txt
		cat /tmp/tmp.txt > /root/Cases/$domain/tmp-$domain.txt 
		rm /tmp/tmp.txt	
	else
		cat /root/Cases/$domain/decloud-$domain.txt | grep "Checking" | cut -d" " -f4 | sed 's/<BR>/\n/' | sort -u | tee /root/Cases/$domain/tmp-$domain.txt
	fi
	gedit /root/Cases/$domain/tmp-$domain.txt &		

	if zenity --question --text="Would you like to open the findings in a browser?"; then
		while read links; do 
		    echo "Opening: $links"; screen -d -m firefox $links
		done < $FILE
		echo "Please wait for Firefox to open..."
	else
		echo "Done."
	fi 

	#Run Tool 
	mkdir /root/Cases/$domain/download-files
	metagoofil -d $domain -w -t pdf,doc,xls,ppt,docx,xlsx,pptx -o "/root/Cases/$domain/download-files" |tee >(zenity --progress --pulsate --no-cancel --auto-close --text="Metagoofil download files, please wait...")
	thunar /root/Cases/$domain >/dev/null 2>&1
	exit
	
fi
